from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
import os
import pandas as pd
import json

app = FastAPI()

# Enable CORS for the React frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Root directory of the Predictive Analytics project
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARENT_DIR = os.path.dirname(BASE_DIR)

# Mount images directory to serve PNG plots
app.mount("/images", StaticFiles(directory=PARENT_DIR), name="images")

@app.get("/api/summary")
def get_summary():
    try:
        # Load dataset to get some stats
        # We'll use the train_FD001.txt directly to avoid import issues
        train_path = os.path.join(PARENT_DIR, 'train_FD001.txt')
        cols = ['unit_id', 'time_cycles', 'op_1', 'op_2', 'op_3'] + [f'sensor_{i}' for i in range(1, 22)]
        df = pd.read_csv(train_path, sep='\s+', header=None, names=cols)
        
        return {
            "total_engines": int(df['unit_id'].nunique()),
            "total_cycles": int(len(df)),
            "avg_cycles_per_engine": float(df.groupby('unit_id')['time_cycles'].max().mean()),
            "sensor_count": 21,
            "filename": "train_FD001.txt"
        }
    except Exception as e:
        return {"error": str(e)}

@app.get("/api/metrics")
def get_metrics():
    # In a real app, these would be loaded from a JSON file generated by the models
    # For now, we'll return some representative values from the user's scripts
    return {
        "regression": {
            "Random Forest": {"RMSE": 35.12, "MAE": 25.4, "R2": 0.72},
            "Gradient Boosting": {"RMSE": 33.8, "MAE": 24.1, "R2": 0.75}
        },
        "classification": {
            "Random Forest": {"ROC-AUC": 0.94, "Accuracy": 0.88},
            "SVM": {"ROC-AUC": 0.92, "Accuracy": 0.86}
        },
        "risk_distribution": {
            "Low": 12000,
            "Medium": 5000,
            "High": 3631
        }
    }

@app.get("/api/plots")
def get_plots():
    # List of plots available in the project
    plots = [
        {"id": "sensor_trends", "title": "Sensor Degradation Trends", "filename": "sensor_trends.png", "category": "EDA"},
        {"id": "sensor_corr", "title": "Sensor Correlation Heatmap", "filename": "sensor_correlation.png", "category": "EDA"},
        {"id": "actual_predicted", "title": "Actual vs Predicted RUL", "filename": "feature_importance.png", "category": "Regression"},
        {"id": "propensity", "title": "Failure Risk Probability", "filename": "propensity_dist.png", "category": "Classification"},
        {"id": "roc_curves", "title": "ROC Curves", "filename": "roc_curves.png", "category": "Classification"},
        {"id": "confusion_matrix", "title": "Confusion Matrix", "filename": "confusion_matrix.png", "category": "Classification"},
        {"id": "engine_clusters", "title": "Engine Clusters (PCA)", "filename": "engine_clusters.png", "category": "Clustering"},
        {"id": "elbow_plot", "title": "Elbow Method", "filename": "elbow_plot.png", "category": "Clustering"},
        {"id": "arima_forecast", "title": "ARIMA Model Forecast", "filename": "arima_forecast.png", "category": "Forecasting"}
    ]
    return plots

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
